apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: book-import
  name: book-import
spec:
  automountServiceAccountToken: false
  replicas: 3
  selector:
    matchLabels:
      name: book-import
  template:
    metadata:
      labels:
        name: book-import
    spec:
      containers:
      - image: quay.io/jpacker/hugo-nginx:latest
        name: book-import
        automountServiceAccountToken: false
        ports:
        - containerPort: 8080
          name: http-server
        resources:
          requests:
            cpu: "2"
            memory: "1Gi"
          limits:
            cpu: "4"
            memory: "2Gi"
